#!/usr/bin/env python3
"""Compatibility facade for the Context Profiler package.

Existing hooks and shell shims import from this module. New code should prefer
the narrower modules under ``context_profiler``.
"""
from __future__ import annotations

from context_profiler.analysis import (
    build_forensics,
    build_agent_runs,
    build_recommendations,
    build_turns,
    compute_stats,
    event_detail,
    event_matches_advice_ignore,
    filter_ignored_file_agg,
    filter_visible_file_agg,
    filter_visible_tool_calls,
    matches_advice_ignore_path,
)
from context_profiler.config import (
    CLAUDE_PROJECTS_DIR,
    CODEX_SESSIONS_DIR,
    CONFIG_PATH,
    DEFAULT_CONFIG,
    DEFAULT_MAX_CONTEXT_TOKENS,
    PROFILE_DIR,
    configured_sources,
    ensure_config,
    is_enabled,
    load_config,
    read_json,
    save_config,
    utc_now,
)
from context_profiler.formatting import (
    estimate_tokens,
    fmt_bytes,
    fmt_tokens,
    git_branch_for,
    token_color,
    ts_to_epoch,
)
from context_profiler.importers.claude import (
    import_claude_transcript,
    import_latest_claude_profiles,
    latest_claude_transcripts,
    normalize_claude_tool_event,
)
from context_profiler.importers.codex import (
    CodexTranscriptImporter,
    import_codex_transcript,
    import_latest_codex_profiles,
    latest_codex_transcripts,
)
from context_profiler.storage import (
    append_event,
    cleanup_old_codex_transcripts,
    cleanup_old_profiles,
    filter_profiles_by_session,
    file_signature,
    get_all_profile_files,
    get_all_profiles,
    get_latest_session,
    load_events,
    mark_transcript_imported,
    profile_matches_session,
    profile_mtime,
    profile_part_paths,
    profile_path,
    profile_source,
    run_auto_cleanup,
    safe_session_id,
    set_profile_mtime,
    transcript_import_current,
    write_profile,
)
from context_profiler.session_index import (
    format_table_timestamp,
    refresh_session_index,
    session_id_for_profile,
    session_relationship_label,
    session_relationship_maps,
    sort_session_rows_by_start,
    timestamp_epoch,
)

__all__ = [
    "CODEX_SESSIONS_DIR",
    "CLAUDE_PROJECTS_DIR",
    "CONFIG_PATH",
    "DEFAULT_CONFIG",
    "DEFAULT_MAX_CONTEXT_TOKENS",
    "PROFILE_DIR",
    "CodexTranscriptImporter",
    "append_event",
    "build_forensics",
    "build_agent_runs",
    "build_recommendations",
    "build_turns",
    "cleanup_old_codex_transcripts",
    "cleanup_old_profiles",
    "compute_stats",
    "configured_sources",
    "ensure_config",
    "estimate_tokens",
    "event_detail",
    "event_matches_advice_ignore",
    "filter_ignored_file_agg",
    "filter_profiles_by_session",
    "file_signature",
    "get_all_profile_files",
    "filter_visible_file_agg",
    "filter_visible_tool_calls",
    "format_table_timestamp",
    "fmt_bytes",
    "fmt_tokens",
    "get_all_profiles",
    "get_latest_session",
    "git_branch_for",
    "import_claude_transcript",
    "import_codex_transcript",
    "import_latest_claude_profiles",
    "import_latest_codex_profiles",
    "is_enabled",
    "latest_claude_transcripts",
    "latest_codex_transcripts",
    "load_config",
    "load_events",
    "mark_transcript_imported",
    "matches_advice_ignore_path",
    "normalize_claude_tool_event",
    "profile_matches_session",
    "profile_mtime",
    "profile_part_paths",
    "profile_path",
    "profile_source",
    "refresh_session_index",
    "run_auto_cleanup",
    "read_json",
    "safe_session_id",
    "session_id_for_profile",
    "session_relationship_label",
    "session_relationship_maps",
    "set_profile_mtime",
    "save_config",
    "sort_session_rows_by_start",
    "token_color",
    "transcript_import_current",
    "ts_to_epoch",
    "timestamp_epoch",
    "utc_now",
    "write_profile",
]
